language: android
sudo: false
branches:
  only:
    - master
env:
    - secure: "oxO/WejcfoGBUlQArNtIG6Sk7SJvbtcYr4G3EEELZaKZkbfrEKqjPBvrrVXy/Aik8nGL9AbmbZNKjGk2IJnLIr2Axd2wYr3ME6dnwBtOC6IUi10fAF3B7WnD5Vmbs5VHsH5UfoaswEKnH6LwMkzn/UDOKtLqeGVut0JX0ZoyB8s="
cache:
    directories:
    -  $HOME/gradle-2.2.1

before_install:
- chmod +x install_gradle.sh
- source ./install_gradle.sh

script: gradle :app-snapshot:build

after_success:
- git config --global user.email "harry-chen@outlook.com"
- git config --global user.name "PAPDT Robot"
- export GIT_TAG=snapshot-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")_${TRAVIS_BUILD_NUMBER}_$(git log --format="%h" -n 1)
- git tag $GIT_TAG
- git push --quiet https://$GITHUBKEY@github.com/PaperAirplane-Dev-Team/BlackLight.git $GIT_TAG

android:
  components:
  - build-tools-21.1.2
  - android-21
  - extra-android-support
  - extra-android-m2repository

deploy:
  provider: releases
  api_key:
    secure: "bBFMDthm2NQuUCXfSRw8EvkyN7seHGxD8BvsvqudSuPpmSTNRcA1JJuANeH7WVMwJjKkySVCf+SjMbHeGzahRRo7COsQ4D70q8ctad9lo1bLwt2UvgFB+c1ux6jzixsGTcCTfmKGYKDmU+iOZ7ES4t45iPsO0VUQYO8hT2fVN+0="
  file: app-snapshot/build/outputs/apk/app-snapshot-debug.apk
  skip_cleanup: true
  on:
    repo: PaperAirplane-Dev-Team/BlackLight
